//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StretchGarageDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingPlace
    {
        public ParkingPlace()
        {
            this.ParkedCars = new HashSet<ParkedCar>();
        }
    
        public int Id { get; set; }
        public decimal Lat { get; set; }
        public decimal Long { get; set; }
        public int ZoneId { get; set; }
        public int ParkingSpots { get; set; }
    
        public virtual ICollection<ParkedCar> ParkedCars { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
