//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StretchGarageDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.ParkedCars = new HashSet<ParkedCar>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public int ZoneId { get; set; }
        public Nullable<System.DateTime> EnteredZone { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Long { get; set; }
    
        public virtual ICollection<ParkedCar> ParkedCars { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
