//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StretchGarageDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public Zone()
        {
            this.ParkingPlaces = new HashSet<ParkingPlace>();
            this.Units = new HashSet<Unit>();
        }
    
        public int Id { get; set; }
        public int Size { get; set; }
        public int PollFrequency { get; set; }
        public bool CheckSpeed { get; set; }
        public Nullable<int> Speed { get; set; }
    
        public virtual ICollection<ParkingPlace> ParkingPlaces { get; set; }
        public virtual ICollection<Unit> Units { get; set; }
    }
}
